### PR TITLE
Removed missing test subdirs from bsconfig.json

### LINKED ISSUE #20: Mysterious error with `-make-world`
```
:;  node_modules/.bin/bsb -make-world
    Regenerating build spec : File not found
    Fatal error: exception Sys_error("tests/fetch: No such file or directory")
    Error happened when running command .../reason-js/node_modules/bs-platform/bin/bsb.exe with args [ '-make-world' ]
```

It seems like it's looking for the directory structure in `src/` to be mirrored in `tests/`.

```
:;  cp -a src/fetch/ tests/fetch/
:;  node_modules/.bin/bsb -make-world
    Regenerating build spec : File not found
    Fatal error: exception Sys_error("tests/gl: No such file or directory")
    Error happened when running command /Users/solidsnack/Downloads/reason-js/node_modules/bs-platform/bin/bsb.exe with args [ '-make-world' ]
```

How does the `.re` code get translated to `.ml`?

### PR DESCRIPTION
**Pull request by glennsl**
Should fix #20

### CODE REVIEW

**Comment by solidsnack** [comment]
👍  Works on my machine.

**Comment by glennsl** [comment]
Thanks!

cc @chenglou could you merge this?

**Comment by chenglou** [comment]
@glennsl weird, these dirs don't exist? How did that pass before?

**Comment by glennsl** [comment]
No they don't exist yet, though they should, and should also have lots of tests in them :)

I assume the latest release of bs changed how directories are traversed.

**Pull request merged**
